Mysql : 
    
    1. Create a table attribute dataset and dress dataset
    2. Do a bulk load for these two table for respective dataset 
    3. read these dataset in pandas as a dataframe 
    4. Convert attribute dataset in json format 
    5. Store this dataset into mongodb
    6. in sql task try to perform left join operation with attrubute dataset and dress dataset on column Dress_ID
    7. Write a sql query to find out how many unique dress that we have based on dress id 
    8. Try to find out how mnay dress is having recommendation 0
    9. Try to find out total dress sell for individual dress id 
    10. Try to find out a third highest most selling dress id 
    
    Data Set file: Attribute_Dataset and Dress_Sales

## 1. Create a table attribute dataset and dress dataset

In [1]:
import mysql.connector as conn

mydb = conn.connect(host="localhost", user="root", password="rootroot")  # to establish the databases
print(mydb)
cursor = mydb.cursor()

<mysql.connector.connection.MySQLConnection object at 0x7fa7296b3670>

In [2]:
cursor.execute("show databases")
print(cursor.fetchall())

[('attribute_dataset',), ('bank',), ('Dress_Sales',), ('information_schema',), ('mysql',), ('performance_schema',), ('student',), ('sys',)]

In [10]:
cursor.execute("create database if not exists attribute_dataset")

cursor.execute("create table attribute_dataset.dress_details(Dress_ID int(20),style varchar(30),price varchar(30),rating float(20),size varchar(30),season varchar(30),neckline varchar(30),sleeveslength varchar(30),waiseline varchar(30),material varchar(30),fabrictype varchar(30),decoration varchar(30),patterntype varchar(30),recommendation int(5))")

cursor.execute("insert into attribute_dataset.dress_details values(1006032852,'Sexy','Low',4.6,'M','Summer','o-neck','sleevless', 'empire' ,'null', 'chiffon', 'ruffles', 'animal', 1)")

mydb.commit()

## 3. read these dataset in pandas as a dataframe

In [3]:
import pandas as pd

In [4]:
df = pd.read_csv('/Users/rajaiswal/Desktop/learning/Fullstack_Datascience_Ineuron/DataFiles/Attribute_DataSet.csv')
df1 = pd.read_csv('/Users/rajaiswal/Desktop/learning/Fullstack_Datascience_Ineuron/DataFiles/Dress_Sales.csv')

In [5]:
df

,Dress_ID,Style,Price,Rating,Size,Season,NeckLine,SleeveLength,waiseline,Material,FabricType,Decoration,Pattern Type,Recommendation
0,1006032852,Sexy,Low,4.6,M,Summer,o-neck,sleevless,empire,NaN,chiffon,ruffles,animal,1
1,1212192089,Casual,Low,0.0,L,Summer,o-neck,Petal,natural,microfiber,NaN,ruffles,animal,0
2,1190380701,vintage,High,0.0,L,Automn,o-neck,full,natural,polyster,NaN,NaN,print,0
3,966005983,Brief,Average,4.6,L,Spring,o-neck,full,natural,silk,chiffon,embroidary,print,1
4,876339541,cute,Low,4.5,M,Summer,o-neck,butterfly,natural,chiffonfabric,chiffon,bow,dot,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
495,713391965,Casual,Low,4.7,M,Spring,o-neck,full,natural,polyster,NaN,NaN,solid,1
496,722565148,Sexy,Low,4.3,free,Summer,o-neck,full,empire,cotton,NaN,NaN,NaN,0
497,532874347,Casual,Average,4.7,M,Summer,v-neck,full,empire,cotton,NaN,lace,solid,1
498,655464934,Casual,Average,4.6,L,winter,boat-neck,sleevless,empire,silk,broadcloth,applique,print,1
499,919930954,Casual,Low,4.4,free,Summer,v-neck,short,empire,cotton,Corduroy,lace,solid,0

In [6]:
df1

,Dress_ID,29/08/13,31/08/13,09/02/13,09/04/13,09/06/13,09/08/13,09/10/13,09/12/13,14/09/13,...,24/09/13,26/09/13,28/09/13,30/09/13,10/02/13,10/04/13,10/06/13,10/08/10,10/10/13,10/12/13
0,1006032852,2114,2274,2491,2660,2727,2887,2930,3119,3204,...,3554,3624.0,3706,3746.0,3795.0,3832.0,3897,3923.0,3985.0,4048
1,1212192089,151,275,570,750,813,1066,1164,1558,1756,...,2710,2942.0,3258,3354.0,3475.0,3654.0,3911,4024.0,4125.0,4277
2,1190380701,6,7,7,7,8,8,9,10,10,...,11,11.0,11,11.0,11.0,11.0,11,11.0,11.0,11
3,966005983,1005,1128,1326,1455,1507,1621,1637,1723,1746,...,1878,1892.0,1914,1924.0,1929.0,1941.0,1952,1955.0,1959.0,1963
4,876339541,996,1175,1304,1396,1432,1559,1570,1638,1655,...,2032,2156.0,2252,2312.0,2387.0,2459.0,2544,2614.0,2693.0,2736
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
495,713391965,0,0,0,560,554,544,537,525,519,...,400,388.0,360,364.0,372.0,377.0,380,382.0,384.0,285
496,722565148,0,0,0,875,866,861,854,850,844,...,859,866.0,882,888.0,895.0,898.0,906,913.0,919.0,931
497,532874347,0,0,0,734,728,726,715,694,690,...,616,597.0,586,569.0,561.0,555.0,551,546.0,535.0,520
498,655464934,0,0,0,254,259,261,263,268,270,...,257,256.0,255,254.0,253.0,250.0,249,249.0,249.0,248
499,919930954,0,0,0,538,545,558,563,578,585,...,628,632.0,639,645.0,651.0,655.0,660,668.0,674.0,680

## 4. Convert attribute dataset in json format

In [36]:
record = df.to_json('attribute_dataset.json')

In [37]:
record1 = df1.to_json('dress_sales.json')

## 5. Store this dataset into mongodb

In [42]:
import pymongo
import json
from pymongo import InsertOne

url = "mongodb://localhost:27017/"

db_name = "attribute_dataset"

client = pymongo.MongoClient(url)

dataBase = client[db_name]

# creating collection inside the database (collection is nothing but the table)
collection = dataBase["attribute_dataset"]

requesting = []

# storing table attribute dataset
with open(r"/Users/rajaiswal/Desktop/learning/Fullstack_Datascience_Ineuron/Tasks/attribute_dataset.json") as f:
    for jsonObj in f:
        myDict = json.loads(jsonObj)
        requesting.append(InsertOne(myDict))

result = collection.bulk_write(requesting)
print("Sucessful")
client.close()

Sucessful

In [41]:
import pymongo
import json
from pymongo import InsertOne

url = "mongodb://localhost:27017/"

db_name = "dress_sales"

client = pymongo.MongoClient(url)

dataBase = client[db_name]

# creating collection inside the database (collection is nothing but the table)
collection = dataBase["dress_sales"]

requesting = []

# storing table attribute dataset
with open(r"/Users/rajaiswal/Desktop/learning/Fullstack_Datascience_Ineuron/Tasks/dress_sales.json") as f:
    for jsonObj in f:
        myDict = json.loads(jsonObj)
        requesting.append(InsertOne(myDict))

result = collection.bulk_write(requesting)
print("Sucessful")
client.close()

Sucessful

## 6. Perform left join operation with attrubute dataset and dress dataset on column Dress_ID

In [47]:
import mysql.connector as conn

mydb = conn.connect(host="localhost", user="root", password="rootroot")  # to establish the databases
cursor = mydb.cursor()  # to create a cursor in database

l = []
cursor.execute('use attribute_dataset')

# query to perform left join
q1 = 'select dress_details.Dress_ID, dress_details.style, dress_details.price from dress_details left join dress_sales on  dress_details.Dress_ID = dress_sales.Dress_ID order by dress_details.Dress_ID;'
cursor.execute(q1)

for i in cursor.fetchall():
    l.append(i)

print(l)

[(444282011, 'party', 'very-high'), (510519284, 'Casual', 'Low'), (511503677, 'Casual', 'Low'), (520233308, 'Casual', 'Low'), (522776523, 'Casual', 'low'), (531254082, 'Casual', 'low'), (532874347, 'Casual', 'Average'), (535968075, 'work', 'Medium'), (537463111, 'Casual', 'Average'), (541172235, 'Casual', 'Average'), (547555172, 'cute', 'Low'), (549159213, 'Casual', 'Average'), (549159213, 'Casual', 'Average'), (549159213, 'Casual', 'Average'), (549159213, 'Casual', 'Average'), (549401113, 'Casual', 'Low'), (549437715, 'Casual', 'Average'), (550959163, 'Casual', 'Low'), (555727400, 'Casual', 'low'), (560474456, 'Sexy', 'low'), (560474456, 'Sexy', 'low'), (560474456, 'Sexy', 'low'), (560474456, 'Sexy', 'low'), (573923366, 'sexy', 'Low'), (578702321, 'Sexy', 'low'), (579010251, 'party', 'high'), (593007494, 'Casual', 'Low'), (598523814, 'Casual', 'Average'), (600514129, 'cute', 'Medium'), (605122868, 'Casual', 'Average'), (609889168, 'party', 'high'), (616295248, 'party', 'Medium'), (618420156, 'party', 'very-high'), (619817668, 'party', 'high'), (619996560, 'party', 'Average'), (622667306, 'party', 'very-high'), (624314841, 'cute', 'Average'), (629131530, 'cute', 'Low'), (630561922, 'Casual', 'Low'), (636178374, 'party', 'Medium'), (638423913, 'Casual', 'Medium'), (640823350, 'Casual', 'Low'), (641665398, 'Casual', 'Low'), (655464934, 'Casual', 'Average'), (658650071, 'Casual', 'Medium'), (659466129, 'Casual', 'Average'), (660016574, 'Casual', 'very-high'), (660179663, 'Casual', 'Average'), (661795386, 'Brief', 'Low'), (662727740, 'party', ''), (663993130, 'Casual', 'Medium'), (674192921, 'Casual', 'Low'), (674885710, 'Casual', 'high'), (675980168, 'bohemian', 'Average'), (676827184, 'Casual', 'high'), (679415939, 'Casual', 'Low'), (680070369, 'Casual', 'Low'), (682561447, 'party', 'very-high'), (684561284, 'party', 'very-high'), (685606338, 'Casual', 'Medium'), (688966772, 'Casual', 'Average'), (689406468, 'party', 'very-high'), (689486739, 'party', 'very-high'), (692445545, 'Casual', 'Low'), (694493217, 'Casual', 'low'), (699651184, 'Casual', 'Low'), (699738864, 'Casual', 'low'), (699738864, 'Casual', 'low'), (699738864, 'Casual', 'Low'), (699738864, 'Casual', 'Low'), (702984554, 'Casual', 'Average'), (703395323, 'Casual', 'Medium'), (707537639, 'Casual', 'low'), (709353440, 'cute', 'Average'), (709353440, 'cute', 'Average'), (709353440, 'cute', 'Average'), (709353440, 'cute', 'Average'), (710089916, 'Brief', 'Average'), (711045472, 'Casual', 'Average'), (711704151, 'cute', 'Average'), (713391965, 'Casual', 'Low'), (713439584, 'Sexy', 'Average'), (720087997, 'Casual', 'Low'), (720099861, 'Casual', 'Average'), (720665176, 'Casual', 'Average'), (722020708, 'Casual', 'Low'), (722565148, 'Sexy', 'low'), (722565148, 'Sexy', 'low'), (722565148, 'Sexy', 'Low'), (722565148, 'Sexy', 'Low'), (724177834, 'Casual', 'low'), (726446177, 'party', 'very-high'), (727676110, 'Casual', 'low'), (727676110, 'Casual', 'low'), (727676110, 'Casual', 'low'), (727676110, 'Casual', 'low'), (727820291, 'Casual', 'low'), (730603782, 'party', 'Average'), (732184480, 'party', 'very-high'), (732650169, 'cute', 'Low'), (732736124, 'work', 'Average'), (732757918, 'Sexy', 'Average'), (733025646, 'Sexy', 'low'), (733025646, 'Sexy', 'low'), (733025646, 'Casual', 'Low'), (733025646, 'Casual', 'Low'), (733134203, 'vintage', 'Medium'), (733134203, 'vintage', 'Medium'), (733134203, 'Casual', 'low'), (733134203, 'Casual', 'low'), (733715437, 'Brief', 'Average'), (733715437, 'Brief', 'Average'), (733715437, 'Brief', 'Average'), (733715437, 'Brief', 'Average'), (734061929, 'Casual', 'Low'), (735635595, 'Sexy', 'Average'), (736076633, 'party', 'very-high'), (736813752, 'party', 'high'), (737461130, 'Casual', 'Average'), (737538048, 'Casual', 'Average'), (738079582, 'Casual', 'Low'), (743417270, 'Sexy', 'low'), (743485617, 'cute', 'Average'), (743729613, 'Casual', 'Average'), (746255172, 'Casual', 'Average'), (746518490, 'Sexy', 'Low'), (747381880, 'vintage', 'Average'), (749031896, 'vintage', 'Average'), (750670078, 'Casual', 'Low'), (751049573, 'cute', 'Average'), (751364614, 'party', 'Average'), (751364623, 'party', 'Average'), (751776863, 'Casual', 'Average'), (754138176, 'party', 'very-high'), (754316257, 'Casual', 'Low'), (755078866, 'Casual', 'Low'), (756492184, 'Casual', 'Average'), (756620535, 'Casual', 'Low'), (757260823, 'Casual', 'Low'), (763708514, 'sexy', 'Average'), (764321904, 'Sexy', 'Average'), (765264430, 'Brief', 'Average'), (765350508, 'Casual', 'low'), (767971724, 'Brief', 'Average'), (768517084, 'Sexy', 'Average'), (771972560, 'work', 'low'), (774130360, 'Casual', 'Average'), (783980024, 'Casual', 'Average'), (785830491, 'cute', 'Average'), (789373177, 'Casual', 'Average'), (793162246, 'Casual', 'Average'), (793162246, 'Casual', 'Average'), (793162246, 'Casual', 'Average'), (793162246, 'Casual', 'Average'), (797673346, 'Casual', 'Low'), (798898277, 'bohemian', 'Low'), (799301728, 'vintage', 'Average'), (801216472, 'cute', 'high'), (801861988, 'vintage', 'Average'), (805438829, 'Sexy', 'Low'), (809344968, 'party', 'Medium'), (813753347, 'Casual', 'Low'), (817353671, 'bohemian', 'Low'), (817870237, 'Sexy', 'Low'), (817945281, 'Casual', 'low'), (818295153, 'bohemian', 'low'), (818505402, 'Casual', 'low'), (819651586, 'bohemian', 'Low'), (822053936, 'party', 'Average'), (822081627, 'Sexy', 'Average'), (822176645, 'Casual', 'Average'), (825341937, 'party', 'high'), (827791337, 'party', 'High'), (828623528, 'Casual', 'Average'), (828790972, 'party', 'Average'), (828949946, 'Casual', 'High'), (829087315, 'cute', 'Average'), (830467746, 'bohemian', 'Medium'), (832090686, 'cute', 'Average'), (832191944, 'cute', 'Medium'), (832391864, 'Casual', 'Average'), (832949213, 'Casual', 'Low'), (835787654, 'Casual', 'Average'), (835915937, 'Casual', 'Average'), (836788720, 'fashion', 'Average'), (839305476, 'Casual', 'Low'), (840516484, 'Sexy', 'Average'), (840857118, 'Brief', 'Average'), (841203385, 'Sexy', 'Low'), (841203385, 'Sexy', 'Low'), (841203385, 'Sexy', 'low'), (841203385, 'Sexy', 'low'), (842060995, 'Casual', 'Average'), (845853510, 'Casual', 'Average'), (849613634, 'Casual', 'Average'), (849947393, 'cute', 'Medium'), (850490510, 'Casual', 'Average'), (850586379, 'Brief', 'Average'), (851256794, 'work', 'low'), (851697194, 'bohemian', 'Average'), (851945460, 'Casual', 'Average'), (854444464, 'Casual', 'Average'), (855037000, 'Casual', 'Average'), (855418066, 'Casual', 'Low'), (856139963, 'Casual', 'Low'), (856178100, 'Casual', 'Low'), (857189807, 'Sexy', 'Low'), (857432541, 'Casual', 'Low'), (858212832, 'cute', 'Average'), (859321875, 'Brief', 'Low'), (859922576, 'cute', 'Average'), (860334943, 'Casual', 'Medium'), (860406062, 'Casual', 'Average'), (861001391, 'party', 'high'), (861626197, 'work', 'Average'), (861698160, 'Casual', 'Average'), (861754372, 'Sexy', 'Average'), (862814652, 'Casual', 'Average'), (863336720, 'Casual', 'Average'), (863336720, 'Casual', 'Average'), (863336720, 'Casual', 'Average'), (863336720, 'Casual', 'Average'), (864253055, 'bohemian', 'Average'), (865490824, 'Sexy', 'high'), (866405822, 'bohemian', 'Average'), (868453353, 'Casual', 'Low'), (869138763, 'Casual', 'Average'), (869395176, 'Casual', 'Average'), (869572905, 'Casual', 'Low'), (870994067, 'cute', 'Low'), (870994067, 'cute', 'Low'), (870994067, 'cute', 'Low'), (870994067, 'cute', 'Low'), (871219565, 'Brief', 'Low'), (871620435, 'Brief', 'Low'), (874397327, 'Casual', 'Average'), (875312593, 'Casual', 'Average'), (875608094, 'Casual', 'Low'), (876339541, 'cute', 'Low'), (876708804, 'Sexy', 'Low'), (876708804, 'Sexy', 'Low'), (876708804, 'Sexy', 'Low'), (876708804, 'Sexy', 'Low'), (876761815, 'Casual', 'Low'), (877962269, 'Casual', 'Average'), (879756967, 'Casual', 'Low'), (880692544, 'Casual', 'Average'), (881530990, 'work', 'Average'), (882490248, 'cute', 'Average'), (882975367, 'Sexy', 'Average'), (884147971, 'Casual', 'Medium'), (886351969, 'cute', 'Medium'), (886501087, 'cute', 'low'), (887476609, 'bohemian', 'Low'), (890279029, 'Casual', 'Average'), (890848361, 'vintage', 'Average'), (891103323, 'Casual', 'Average'), (891631697, 'party', 'Average'), (892801580, 'vintage', 'Average'), (893088817, 'Casual', 'Medium'), (893330898, 'Sexy', 'Low'), (895807023, 'cute', 'low'), (896048351, 'Sexy', 'Low'), (896048351, 'Sexy', 'Low'), (896048351, 'Sexy', 'low'), (896048351, 'Sexy', 'low'), (897981100, 'Casual', 'Average'), (898316315, 'party', 'Average'), (898316819, 'party', 'Medium'), (898481530, 'Flare', 'Average'), (898646576, 'Casual', 'Low'), (900108476, 'Casual', 'Low'), (901346821, 'Sexy', 'low'), (902108125, 'Sexy', 'Average'), (903426442, 'sexy', 'Average'), (904781800, 'cute', 'Average'), (905732124, 'Casual', 'low'), (905732124, 'Casual', 'low'), (905732124, 'Casual', 'low'), (905732124, 'Casual', 'low'), (907117649, 'party', 'Average'), (907669618, 'Sexy', 'Average'), (908989488, 'bohemian', 'Average'), (909624960, 'work', 'Average'), (911085061, 'bohemian', 'Low'), (912614690, 'bohemian', 'Low'), (913978120, 'Sexy', 'Medium'), (915238287, 'Casual', 'Low'), (918331326, 'Brief', 'Average'), (918722829, 'Sexy', 'Low'), (919930954, 'Casual', 'Low'), (920902282, 'Casual', 'Average'), (923915314, 'Casual', 'Average'), (923983419, 'Casual', 'Average'), (924108301, 'Casual', 'Low'), (926480831, 'Sexy', 'Average'), (929503394, 'vintage', 'Average'), (929797706, 'Casual', 'Low'), (929898500, 'work', 'Average'), (932375745, 'Casual', 'low'), (932913675, 'Casual', 'Low'), (933231033, 'Casual', 'Average'), (933231033, 'Casual', 'Average'), (933231033, 'party', 'Average'), (933231033, 'party', 'Average'), (933413410, 'Casual', 'Average'), (933864550, 'Sexy', 'low'), (933926000, 'Casual', 'Average'), (933951149, 'party', 'Average'), (934830377, 'bohemian', 'Low'), (935827969, 'cute', 'Average'), (936425780, 'work', 'Average'), (937046375, 'Casual', 'Average'), (939250541, 'Casual', 'Average'), (939389270, 'Casual', 'Average'), (939422280, 'cute', 'Average'), (939770391, 'Casual', 'Average'), (940918554, 'Sexy', 'low'), (941190190, 'Casual', 'Average'), (941333009, 'cute', 'Average'), (941564304, 'Sexy', 'Average'), (942245416, 'Casual', 'Average'), (942808364, 'cute', 'Low'), (943188872, 'bohemian', 'very-high'), (943414146, 'Sexy', 'Average'), (943844640, 'Brief', 'Average'), (944264938, 'Sexy', 'Low'), (944641715, 'bohemian', 'Low'), (944656411, 'vintage', 'Low'), (944930838, 'vintage', 'low'), (945651303, 'Casual', 'Low'), (946741571, 'bohemian', 'Average'), (949226757, 'Casual', 'Low'), (949336768, 'Casual', 'high'), (950048509, 'Casual', 'high'), (951280194, 'work', 'Average'), (952724683, 'party', 'Average'), (953168456, 'cute', 'Average'), (955188745, 'Casual', 'Average'), (955679920, 'Sexy', 'Average'), (956453735, 'cute', 'low'), (956758119, 'Casual', 'Low'), (957723897, 'sexy', 'Low'), (958270190, 'Casual', 'Low'), (959052557, 'Casual', 'Average'), (961230947, 'work', 'Average'), (961972778, 'Casual', 'very-high'), (963684109, 'party', 'very-high'), (964917582, 'Casual', 'Average'), (965817793, 'Casual', 'low'), (966005983, 'Brief', 'Average'), (966030991, 'party', 'Average'), (967191118, 'Sexy', 'Low'), (967999477, 'Sexy', 'Low'), (968294356, 'Casual', 'Average'), (970655043, 'bohemian', 'Low'), (971387676, 'Casual', 'Low'), (973481686, 'vintage', 'Average'), (974438263, 'cute', 'Low'), (974746803, 'Casual', 'Average'), (974775647, 'Casual', 'Low'), (975877364, 'work', 'Average'), (976975672, 'Novelty', 'Average'), (976975672, 'Novelty', 'Average'), (976975672, 'Novelty', 'Average'), (976975672, 'Novelty', 'Average'), (977173764, 'Casual', 'Average'), (978773911, 'Brief', 'Average'), (980295760, 'Casual', 'Low'), (981437831, 'Casual', 'Average'), (985292672, 'bohemian', 'Low'), (990559192, 'Brief', 'Average'), (995644296, 'Sexy', 'Average'), (995802744, 'Sexy', 'Average'), (995964089, 'bohemian', 'Average'), (999081623, 'Casual', 'Average'), (1000425584, 'cute', 'Average'), (1000493051, 'sexy', 'Low'), (1001750851, 'Casual', 'Low'), (1002440915, 'Casual', 'Medium'), (1004212992, 'Sexy', 'Average'), (1006032852, 'Sexy', 'Low'), (1010356223, 'vintage', 'Average'), (1015249105, 'work', 'Average'), (1016250560, 'vintage', 'Average'), (1017484769, 'Sexy', 'Low'), (1017678811, 'Casual', 'low'), (1018110870, 'Sexy', 'Low'), (1018130478, 'Casual', 'Low'), (1019134411, 'Casual', 'Average'), (1019672746, 'vintage', 'Average'), (1019768234, 'vintage', 'Average'), (1021185637, 'vintage', 'Average'), (1021375534, 'cute', 'low'), (1023830972, 'Casual', 'Average'), (1023850025, 'vintage', 'Low'), (1024325244, 'Casual', 'Average'), (1024954013, 'Casual', 'Average'), (1026634314, 'Casual', 'Average'), (1027818824, 'Casual', 'Medium'), (1028061165, 'Casual', 'Average'), (1031230798, 'bohemian', 'Average'), (1031230798, 'bohemian', 'Average'), (1031230798, 'bohemian', 'Average'), (1031230798, 'bohemian', 'Average'), (1032982013, 'Casual', 'Average'), (1032990258, 'party', 'Average'), (1032990258, 'party', 'Average'), (1032990258, 'Casual', 'Average'), (1032990258, 'Casual', 'Average'), (1033144189, 'cute', 'Average'), (1033843327, 'Casual', 'Average'), (1036333255, 'Casual', 'low'), (1036456647, 'Sexy', 'Average'), (1039384371, 'Casual', 'Average'), (1039982741, 'Casual', 'Average'), (1043590098, 'Casual', 'low'), (1044288976, 'Sexy', 'Average'), (1044683061, 'party', 'very-high'), (1051749304, 'work', 'Average'), (1052420390, 'vintage', 'Average'), (1053002876, 'work', 'Average'), (1053296757, 'cute', 'High'), (1053467336, 'party', 'Average'), (1054555186, 'party', 'very-high'), (1054679816, 'party', 'Average'), (1055149353, 'Sexy', 'Low'), (1055411544, 'Casual', 'Low'), (1059306768, 'Casual', 'Average'), (1059959935, 'Casual', 'Average'), (1060207186, 'Brief', 'Average'), (1061890181, 'Casual', 'Average'), (1062354779, 'Casual', 'Average'), (1062354779, 'Casual', 'Average'), (1062354779, 'Casual', 'Average'), (1062354779, 'Casual', 'Average'), (1065316076, 'Casual', 'Low'), (1065317917, 'Casual', 'Average'), (1066273951, 'Casual', 'Average'), (1066740059, 'party', 'Average'), (1068332458, 'bohemian', 'Low'), (1069577979, 'Casual', 'Low'), (1069595866, 'sexy', 'Medium'), (1071947910, 'Sexy', 'Average'), (1072477320, 'Casual', 'Low'), (1072784739, 'Casual', 'low'), (1074432879, 'Casual', 'Average'), (1077015977, 'vintage', 'Average'), (1077555214, 'Casual', 'low'), (1078431253, 'Casual', 'Low'), (1078994436, 'Sexy', 'Average'), (1078996836, 'Sexy', 'Low'), (1079373429, 'Casual', 'Average'), (1079373429, 'Casual', 'Average'), (1079373429, 'work', 'Average'), (1079373429, 'work', 'Average'), (1079955163, 'Casual', 'Average'), (1079958917, 'Casual', 'Average'), (1083323104, 'Sexy', 'low'), (1083779666, 'Casual', 'Average'), (1083779666, 'Casual', 'Average'), (1083779666, 'Casual', 'Average'), (1083779666, 'Casual', 'Average'), (1086459983, 'Novelty', 'Average'), (1088674674, 'Casual', 'Low'), (1090993173, 'party', ''), (1091666465, 'Casual', 'Average'), (1091877430, 'party', 'high'), (1096779299, 'Casual', 'Average'), (1097157656, 'Casual', 'Average'), (1097157656, 'Casual', 'Average'), (1097157656, 'Casual', 'Average'), (1097157656, 'Casual', 'Average'), (1097435333, 'Casual', 'Average'), (1097548715, 'vintage', 'Medium'), (1099363892, 'Casual', 'Average'), (1099394392, 'Sexy', 'Low'), (1099696103, 'Casual', 'Average'), (1100974555, 'Sexy', 'Low'), (1104450248, 'Sexy', 'Average'), (1104504876, 'cute', 'Low'), (1107279894, 'party', 'very-high'), (1108073621, 'party', 'Medium'), (1108356000, 'Casual', 'Average'), (1108613896, 'party', 'very-high'), (1109819647, 'Casual', 'Average'), (1113094204, 'Flare', 'Average'), (1113221101, 'Sexy', 'Average'), (1116072373, 'Novelty', 'Medium'), (1117293701, 'party', 'Average'), (1117997056, 'Casual', 'Low'), (1118628066, 'Casual', 'Medium'), (1119360745, 'Casual', 'Average'), (1122989777, 'Brief', 'Low'), (1122991519, 'Sexy', 'Low'), (1124120907, 'Casual', 'Average'), (1124754999, 'Sexy', 'Average'), (1130463523, 'Sexy', 'Medium'), (1130624045, 'Sexy', 'Low'), (1130994272, 'Casual', 'Low'), (1132858821, 'Sexy', 'very-high'), (1135456589, 'Casual', 'Average'), (1139064593, 'Casual', 'high'), (1139843344, 'Sexy', 'Average'), (1140306858, 'Casual', 'Average'), (1146088956, 'Casual', 'Medium'), (1148457078, 'Casual', 'Low'), (1150052066, 'bohemian', 'Average'), (1150275464, 'Casual', 'Low'), (1153442065, 'Novelty', 'Average'), (1155548915, 'vintage', 'High'), (1158347154, 'Casual', 'Average'), (1160536550, 'Casual', 'Average'), (1162628131, 'Casual', 'Low'), (1163040038, 'party', 'high'), (1163826114, 'Sexy', 'Average'), (1166855026, 'Casual', 'Average'), (1167448608, 'cute', 'low'), (1169895668, 'Casual', 'Average'), (1174854264, 'work', 'Average'), (1175184188, 'Casual', 'Average'), (1190380701, 'vintage', 'High'), (1190383536, 'vintage', 'Low'), (1190558632, 'cute', 'Average'), (1193747589, 'party', 'very-high'), (1194626925, 'OL', 'Medium'), (1197204708, 'Casual', 'Low'), (1197211965, 'cute', 'Low'), (1199064757, 'Casual', 'low'), (1199765487, 'Casual', 'Average'), (1199912555, 'Casual', 'Average'), (1206128856, 'Casual', 'Low'), (1210582154, 'sexy', 'Low'), (1211480431, 'Sexy', 'Low'), (1212192089, 'Casual', 'Low'), (1216538883, 'cute', 'Average'), (1217548862, 'vintage', 'Average'), (1219677488, 'Novelty', 'Average'), (1219677488, 'Novelty', 'Average'), (1219677488, 'Novelty', 'Average'), (1219677488, 'Novelty', 'Average'), (1220707172, 'Casual', 'Average'), (1223469038, 'Sexy', 'Average'), (1225512606, 'cute', 'High'), (1235426503, 'Casual', 'Low'), (1246749980, 'vintage', 'Average'), (1246945687, 'Novelty', 'Average'), (1249825438, 'Sexy', 'Average'), (1250787559, 'cute', 'Low'), (1253973206, 'cute', 'Low')]

## 7. Write a sql query to find out how many unique dress that we have based on dress id

In [52]:
import mysql.connector as conn

mydb = conn.connect(host="localhost", user="root", password="rootroot")  # to establish the databases
cursor = mydb.cursor()  # to create a cursor in database

cursor.execute('use attribute_dataset')

# query to count distinct dress id
q1 = 'select count(distinct Dress_ID) from dress_details;'
cursor.execute(q1)
print(cursor.fetchall())

[(475,)]

##  8. Try to find out how many dress is having recommendation 0

In [53]:
import mysql.connector as conn

mydb = conn.connect(host="localhost", user="root", password="rootroot")  # to establish the databases
cursor = mydb.cursor()  # to create a cursor in database

cursor.execute('use attribute_dataset')

# query to count distinct dress id
q1 = 'select count(recommendation) from dress_details where dress_details.recommendation = 0;'
cursor.execute(q1)
print(cursor.fetchall())

[(290,)]

## 9. Try to find out total dress sell for individual dress id

In [54]:
import mysql.connector as conn

mydb = conn.connect(host="localhost", user="root", password="rootroot")  # to establish the databases
cursor = mydb.cursor()  # to create a cursor in database

cursor.execute('use attribute_dataset')

# query to count distinct dress id
q1 = "select Dress_ID ,(`29/08/13`+`31/08/13`+`09/02/13`+`09/04/13`+`09/06/13`+`09/08/13`+`09/10/13`+`09/12/13`+`14/09/13`+`16/09/13`+`18/09/13`+`20/09/13`+`22/09/13`+`24/09/13`+`26/09/13`+`28/09/13`+`30/09/13`+`10/02/13`+`10/04/13`+`10/06/13`+`10/08/10`+`10/10/13`+`10/12/13`) as 'total count' from dress_sales"
cursor.execute(q1)
print(cursor.fetchall())

[(1006032852, 75979), (1212192089, 52256), (1190380701, 223), (966005983, 39691), (876339541, 44077), (1068332458, 457), (1220707172, 7328), (1219677488, 3248), (1113094204, 494), (985292672, 300), (1117293701, 1911), (898481530, 2842), (957723897, 49983), (749031896, 75346), (1055411544, 1095), (1162628131, 2319), (624314841, 47998), (830467746, 401), (840857118, 299), (1113221101, 9998), (861754372, 6175), (856178100, 31467), (1122989777, 5216), (840516484, 42347), (768517084, 107), (1139843344, 518), (1004212992, 48440), (1235426503, 4696), (942808364, 11518), (629131530, 155927), (851945460, 26496), (1150275464, 5738), (1026634314, 18184), (978773911, 23200), (827791337, 41875), (640823350, 29528), (801861988, 32342), (1060207186, 1820), (1054679816, 12987), (941190190, 11693), (943844640, 2999), (661795386, 49173), (875312593, 11817), (971387676, 15506), (1021185637, 4451), (1163826114, 2133), (735635595, 91556), (1175184188, 635), (679415939, 20730), (884147971, 96), (841203385, 3943), (1117997056, 3947), (1160536550, 1341), (828623528, 27364), (763708514, 17079), (1153442065, 5905), (743729613, 10944), (1000493051, 9852), (911085061, 6751), (1174854264, 778), (1053296757, 105), (1033843327, 257), (1083779666, 1565), (746255172, 37083), (1100974555, 5614), (1019134411, 12001), (1072477320, 6722), (638423913, 601), (936425780, 7775), (1146088956, 182), (864253055, 1646), (1210582154, 11403), (926480831, 6835), (757260823, 957), (630561922, 15909), (734061929, 38251), (842060995, 594), (1078431253, 162), (939770391, 134), (943188872, 1871), (1130994272, 2455), (907117649, 24713), (967999477, 7218), (944656411, 7720), (1096779299, 582), (1036333255, 4018), (1065316076, 4464), (995802744, 6707), (1018110870, 8229), (850586379, 7522), (1169895668, 480), (688966772, 17272), (1194626925, 429), (876708804, 2996), (1118628066, 3744), (1027818824, 48), (891103323, 812), (1166855026, 69), (1023850025, 8696), (805438829, 13749), (836788720, 426), (835787654, 7831), (1148457078, 4030), (887476609, 11237), (535968075, 22147), (892801580, 6071), (732650169, 34651), (680070369, 9422), (1002440915, 1843), (737538048, 57543), (1104450248, 3358), (797673346, 17017), (1039982741, 604), (829087315, 7206), (1032990258, 2725), (939422280, 9070), (974746803, 3809), (1018130478, 6620), (956758119, 7868), (861626197, 20839), (1077015977, 150), (817870237, 4536), (1078996836, 1748), (881530990, 11515), (937046375, 3439), (870994067, 3464), (893330898, 7852), (822053936, 3668), (1059959935, 76), (1197204708, 4385), (713439584, 9740), (732736124, 3615), (709353440, 5811), (1031230798, 2846), (1225512606, 270), (1158347154, 1460), (976975672, 2226), (520233308, 11041), (935827969, 1952), (1130624045, 1467), (547555172, 21772), (1083323104, 8830), (955188745, 5761), (1140306858, 2539), (895807023, 7351), (818505402, 1059), (897981100, 2086), (973481686, 9305), (1021375534, 7555), (549437715, 32300), (1097548715, 515), (578702321, 994), (1155548915, 151), (1199064757, 44), (1078994436, 195), (949226757, 3665), (832191944, 109), (869572905, 4765), (896048351, 3572), (854444464, 8291), (1246749980, 6915), (849613634, 424), (1019768234, 8822), (785830491, 434), (832391864, 1012), (1069595866, 80), (733715437, 6559), (828949946, 6160), (765264430, 11259), (722020708, 13804), (980295760, 5632), (913978120, 16361), (1062354779, 3857), (1051749304, 497), (1206128856, 6295), (956453735, 1906), (767971724, 1888), (722565148, 14748), (1167448608, 1208), (549159213, 4697), (940918554, 1870), (522776523, 9414), (658650071, 12607), (560474456, 6109), (1150052066, 4476), (929797706, 204), (886351969, 7793), (1071947910, 114), (813753347, 31663), (733134203, 3636), (851256794, 991), (751049573, 1974), (882490248, 6282), (541172235, 12217), (727676110, 2566), (891631697, 2125), (1059306768, 56), (764321904, 806), (902108125, 3302), (874397327, 4837), (861698160, 2183), (981437831, 1452), (1036456647, 704), (951280194, 8656), (1079373429, 1005), (747381880, 19026), (1099363892, 4352), (941333009, 3320), (819651586, 4225), (1043590098, 2423), (1091666465, 447), (863336720, 3006), (771972560, 7435), (756492184, 1195), (1097157656, 2761), (573923366, 6296), (756620535, 9670), (765350508, 8718), (968294356, 12854), (1017678811, 68), (933231033, 3790), (1199765487, 23), (965817793, 6445), (1074432879, 937), (1132858821, 57), (905732124, 2489), (711045472, 3560), (923983419, 721), (733025646, 13461), (720099861, 14733), (923915314, 6679), (1077555214, 2514), (1216538883, 9493), (531254082, 6087), (890279029, 3678), (995964089, 610), (868453353, 826), (1024954013, 5021), (685606338, 3830), (877962269, 1548), (995644296, 6245), (1066273951, 1551), (822176645, 4834), (659466129, 58), (694493217, 5602), (793162246, 24217), (817945281, 1981), (920902282, 3738), (727820291, 6003), (699738864, 4956), (1197211965, 195), (682561447, 1236), (999081623, 2451), (1108613896, 23), (1054555186, 98), (915238287, 2529), (1107279894, 56), (1163040038, 60), (1091877430, 30), (1053467336, 1282), (609889168, 2728), (662727740, 3892), (963684109, 1296), (619817668, 4140), (1066740059, 1311), (732184480, 1092), (1044683061, 613), (579010251, 1323), (751364623, 1645), (898316819, 1607), (622667306, 1619), (809344968, 6060), (754138176, 3193), (674192921, 3069), (726446177, 2082), (1193747589, 40), (676827184, 1891), (619996560, 3224), (618420156, 1928), (689486739, 511), (751364614, 2164), (825341937, 2088), (736813752, 804), (636178374, 1929), (743485617, 2102), (933951149, 1810), (684561284, 1406), (616295248, 2509), (736076633, 2056), (1108073621, 112), (1053002876, 541), (444282011, 1732), (949336768, 610), (961972778, 65), (893088817, 677), (952724683, 108), (855037000, 787), (660016574, 1287), (738079582, 2355), (861001391, 1344), (1099696103, 1506), (1044288976, 541), (890848361, 1710), (929503394, 4847), (1015249105, 5205), (707537639, 16225), (702984554, 1795), (896048351, 3170), (1023830972, 1113), (959052557, 4207), (1246945687, 1034), (510519284, 2888), (1079958917, 2715), (1024325244, 539), (841203385, 3251), (1104504876, 1000), (1010356223, 1070), (1031230798, 2514), (908989488, 45), (822081627, 11181), (1116072373, 1284), (856139963, 1261), (1032982013, 1452), (879756967, 11698), (912614690, 672), (1072784739, 2421), (945651303, 1371), (858212832, 9045), (1219677488, 1936), (886501087, 161), (944264938, 1644), (918722829, 1878), (750670078, 11359), (1028061165, 1305), (699738864, 4246), (905732124, 2244), (961230947, 1490), (849947393, 3792), (857432541, 1785), (1088674674, 1098), (939250541, 1866), (876708804, 2928), (1032990258, 2284), (880692544, 1299), (958270190, 893), (732757918, 15484), (898646576, 4069), (950048509, 932), (754316257, 3231), (598523814, 7730), (774130360, 42), (555727400, 8339), (537463111, 4533), (933864550, 2479), (944930838, 2854), (901346821, 1015), (818295153, 1458), (733134203, 3261), (943414146, 11741), (709353440, 5112), (1190383536, 2492), (869138763, 1055), (977173764, 1360), (918331326, 1785), (733715437, 5494), (955679920, 2125), (862814652, 2139), (799301728, 1444), (1039384371, 1628), (746518490, 4855), (720665176, 135), (1001750851, 410), (882975367, 3166), (1069577979, 1293), (1079373429, 966), (711704151, 9443), (876761815, 1310), (1062354779, 3441), (727676110, 2422), (845853510, 3570), (832090686, 5940), (839305476, 3017), (855418066, 2032), (1211480431, 2719), (946741571, 5910), (724177834, 9202), (975877364, 80), (851697194, 3463), (1108356000, 254), (871219565, 1559), (1250787559, 40), (942245416, 312), (900108476, 1381), (1019672746, 5572), (783980024, 4394), (970655043, 2066), (1139064593, 20), (939389270, 3023), (859321875, 2399), (703395323, 20), (1083779666, 1053), (966030991, 253), (866405822, 1163), (941564304, 2950), (1119360745, 99), (932375745, 3506), (789373177, 2495), (1135456589, 784), (932913675, 389), (1217548862, 843), (755078866, 1858), (1052420390, 502), (924108301, 1762), (675980168, 5100), (730603782, 4308), (934830377, 2534), (689406468, 878), (870994067, 2871), (1016250560, 5621), (860334943, 3254), (863336720, 2611), (835915937, 1529), (944641715, 1764), (869395176, 2373), (1097435333, 49), (1124120907, 1200), (1130463523, 871), (560474456, 5487), (907669618, 4), (710089916, 759), (793162246, 19996), (1065317917, 519), (737461130, 9287), (663993130, 1250), (933231033, 3199), (743417270, 2834), (798898277, 9090), (549401113, 4074), (857189807, 416), (1055149353, 680), (1199912555, 969), (1249825438, 1814), (967191118, 286), (871620435, 564), (865490824, 1171), (1079955163, 1828), (600514129, 1706), (976975672, 2953), (720087997, 8979), (699651184, 3042), (605122868, 4398), (1000425584, 1077), (549159213, 5740), (898316315, 20), (1017484769, 690), (733025646, 14546), (909624960, 1318), (1086459983, 3114), (593007494, 6269), (660179663, 3250), (1097157656, 3497), (751776863, 706), (1253973206, 2231), (828790972, 3408), (933413410, 3906), (550959163, 4844), (933926000, 3477), (953168456, 829), (1124754999, 19), (832949213, 1384), (801216472, 552), (929898500, 4909), (850490510, 12966), (1099394392, 569), (674885710, 5007), (1122991519, 2400), (904781800, 1217), (974438263, 122), (875608094, 1938), (1061890181, 220), (1033144189, 1477), (860406062, 4311), (692445545, 5302), (974775647, 1452), (1109819647, 317), (1223469038, 160), (511503677, 12149), (1190558632, 23), (641665398, 199), (964917582, 1356), (859922576, 9975), (817353671, 5286), (990559192, 1427), (713391965, 8915), (722565148, 17508), (532874347, 12606), (655464934, 5167), (919930954, 12312)]

## 10. Try to find out a third highest most selling dress id

In [56]:
import mysql.connector as conn

mydb = conn.connect(host="localhost", user="root", password="rootroot")  # to establish the databases
cursor = mydb.cursor()  # to create a cursor in database

cursor.execute('use attribute_dataset')

q = "select distinct Dress_ID ,(`29/08/13`+`31/08/13`+`09/02/13`+`09/04/13`+`09/06/13`+`09/08/13`+`09/10/13`+`09/12/13`+`14/09/13`+`16/09/13`+`18/09/13`+`20/09/13`+`22/09/13`+`24/09/13`+`26/09/13`+`28/09/13`+`30/09/13`+`10/02/13`+`10/04/13`+`10/06/13`+`10/08/10`+`10/10/13`+`10/12/13`) as 'total count' from dress_sales order by `total count` desc limit 1 offset 2;"

cursor.execute(q)
print(cursor.fetchall())

[(1006032852, 75979)]